language: android
jdk: oraclejdk7

android:
  components:
    - extra-android-m2repository
    - build-tools-22.0.1
    - android-22
  licenses:
    - android-sdk-license-.+

script:
    - ./gradlew clean test